#!/usr/bin/env bash

set -e

tool_source="${BASH_SOURCE[0]}"
while [ -h "$tool_source" ] ; do tool_source="$(readlink "$tool_source")"; done
sdlc_dir="$( cd -P "$( dirname "$tool_source" )" && pwd )"
prj_home="$( cd -P "$( dirname "$sdlc_dir" )" && pwd )"

cd "${prj_home}"

hash mvn 2>/dev/null || {
  echo 'No Maven executable: aborting'
  exit 1
}

mvn_settings_path="${prj_home}/.mvn/settings.xml"
[[ -e "$mvn_settings_path" ]] || {
  echo "Maven settings file '${mvn_settings_path}' not found: aborting"
  exit 1
}

# Comma-delimited list of profiles to activate
mvn_profiles='release'

mvn --no-transfer-progress --batch-mode --activate-profiles "$mvn_profiles" -s "$mvn_settings_path" install deploy \
    -Dhttps.protocols=TLSv1.2 \
    "-DaltDeploymentRepository=nexus.atoito::http://nexus.atoitogroup.it:8081/repository/maven-snapshots" \
    "-DaltReleaseDeploymentRepository=nexus.atoito::http://nexus.atoitogroup.it:8081/repository/maven-releases"
