#!/usr/bin/env bash

set -e

tool_source="${BASH_SOURCE[0]}"
while [ -h "$tool_source" ] ; do tool_source="$(readlink "$tool_source")"; done
sdlc_dir="$( cd -P "$( dirname "$tool_source" )" && pwd )"
prj_home="$( cd -P "$( dirname "$sdlc_dir" )" && pwd )"

cd "${prj_home}"

hash mvn 2>/dev/null || {
  echo 'No Maven executable: aborting'
  exit 1
}

archetype_version=$(mvn org.apache.maven.plugins:maven-help-plugin:3.4.1:evaluate -Dexpression=project.version -q -DforceStdout)

echo "Build archetype version ${archetype_version}"

mvn clean install

mkdir -p target/generate

cd target/generate

mvn archetype:generate -B \
    -DarchetypeGroupId=com.github.enr.archetypes \
    -DarchetypeArtifactId=framework-maven-archetype \
    "-DarchetypeVersion=${archetype_version}" \
    -DgroupId=com.example \
    -DartifactId=myframework \
    -Dpackage=com.example.framework \
    -Dversion=0.0.0

cd myframework

mvn install

echo -n "mvn -Pfmt -X" && pwd
mvn -Pfmt

echo -n "mvn -Pci -X" && pwd
mvn -Pci

mvn org.codehaus.mojo:versions-maven-plugin:2.17.0:display-dependency-updates 

ls -al
